name: Create Release with Zip

on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 设置环境 Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: 下载文件
        run: |
          python ./download.py

      - name: 设置变量
        id: compile
        run: |
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        with:
          name: bgcode${{ env.FILE_DATE }}
          path: ./ruanjian.zip
      - name: Generate release tag
        id: tag
        run: |
          release_tag=$(date +"%Y.%m.%d-%H%M")
          echo "::set-output name=release_tag::$release_tag"
          echo "bgcode" >> release.txt
      
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN}}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ./ruanjian.zip
        
