name: test

on:
  workflow_dispatch:
  schedule:
   - cron: 0 17 * * 5
env:
    TZ: Asia/Shanghai
    UPLOAD_1 : true

jobs:
    build:
      name: 下载
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: 设置环境 Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: "3.8"
        - name: 安装依赖
          run: |
            python -m pip install --upgrade pip
            pip install -r ./requirements.txt
    
        - name: 下载文件
          run: |
            python ./download.py
            
    
        - name: 设置变量
          id: compile
          run: |
            echo "version=$(bash version.sh)" >> $GITHUB_ENV
            echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
            mv ruanjian.zip ./path
            FILE_NAMES=($(ls ./path))
            count=1
            for filename in "${FILE_NAMES[@]}"; do
              echo "FILE_NAME${count}=${filename}" >> $GITHUB_ENV
              ((count++))
            done
      
        - name: 上传文件1
          if: env.UPLOAD_1 == 'true' && !cancelled()
          uses: actions/upload-artifact@main
          with:
              path: ./path/*