name: 下载软件并发布文件

on:
  workflow_dispatch:
env:
    TZ: Asia/Shanghai
jobs:
   test:
       name: Test
       runs-on: ubuntu-latest
       steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
           go-version: '>=1.20.0'
       - name: 安装依赖
         run: |
             git clone https://github.com/bgvioletsky/DownloadApp.git  bg
             cd ./bg/xbs
             go mod tidy && make
             echo "vf">>kk.txt
       - name: 发布到release
         uses: softprops/action-gh-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN}}
         with:
           tag_name: dsa
           body_path: ./bg/xbs/kk.txt
           files: ./bg/xbs/xbs
    
